[package]
name = "dsmc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.3"
num="0.4"
rand="0.8.5"
clap={version="4.0.26",features=["derive"]}